### PR TITLE
120 backend   userprofile location model updated to take array of strings   wait for 118

### PR DESCRIPTION
**Pull request by KaraWatts**
Built models to hold seeded city, state, and country data from [https://github.com/dr5hn/countries-states-cities-database/tree/master](https://github.com/dr5hn/countries-states-cities-database/tree/master).

Swagger is up to date with endpoints for data.

**http://127.0.0.1:8000/api/v1/countries/** pulls a list of all countries givine name and a flag emoji
image
image

**http://127.0.0.1:8000/api/v1/states/{country_name}/** pulls a list of all states from given country giving id and name
image
image

**http://127.0.0.1:8000/api/v1/cities/{state_id}/** pulls a list of all cities from given state giving id and name
image
image

### CODE REVIEW

**Comment by KaraWatts** [comment]
Updated models have all new migrations and fixtures to upload (there's 150k+ cities so it'll take a beat or three).

**Comment by LouisMartin07** [comment]
The code looks awesome, love the flags!

**Comment by KaraWatts** [comment]
yeah they cute ain't they!?

image

**Comment by KaraWatts** [comment]
On hold to discuss usability

**Pull request merged**
